name: Use composite action

on:
  push:
  workflow_dispatch:

jobs:

  composite-test:
    runs-on: ubuntu-latest
    name: Test composite
    steps:
      - uses: actions/checkout@v2
      - id: is_id_needed
        uses: plocket/ALKiln@v3
      - run: echo "Finished using composite action"
