name: Use composite action

on:
  push:
  workflow_dispatch:
    inputs:
      extra_languages:
        description: 'Optional. A list of comma separated language names visible on buttons or links that change the language of the interview. Overrides the EXTRA_LANGUAGES repo secret.'
        default: ''
      tags:
        description: 'Optional. Use a "tag expression" specify which tagged tests to run (https://cucumber.io/docs/cucumber/api/#tag-expressions).'
        default: ''
      alkiln_version:
        description: 'Optional. The version of ALKiln to get from npm.'

jobs:

  composite-test:
    runs-on: ubuntu-latest
    
    # Does all the secret and manual input wrangling need to happen in here instead?
    name: Test composite
    steps:
      - uses: actions/checkout@v2
      - name: Use ALKiln to run tests
        uses: SuffolkLITLab/ALKiln@5c8e88307efd27938797a4e3b4f1a6ff66c92757
        with:
          SERVER_URL: "${{ secrets.SERVER_URL }}"
          PLAYGROUND_EMAIL: "${{ secrets.PLAYGROUND_EMAIL }}"
          PLAYGROUND_PASSWORD: "${{ secrets.PLAYGROUND_PASSWORD }}"
          PLAYGROUND_ID: "${{ secrets.PLAYGROUND_ID }}"
          EXTRA_LANGUAGES: "${{ secrets.EXTRA_LANGUAGES }}"
          DOCASSEMBLE_DEVELOPER_API_KEY: "${{ secrets.DOCASSEMBLE_DEVELOPER_API_KEY }}"
          ALKILN_VERSION: "^4.0.0"
      
      - run: echo "Finished using ALKiln composite action"
