name: Use composite action

on:
  push:
  workflow_dispatch:

jobs:

  composite-test:
    runs-on: ubuntu-latest
        
    name: Test composite
    steps:
      - uses: actions/checkout@v2
      - id: is_id_needed
        uses: plocket/ALKiln@v37
        with:
          SERVER_URL: "${{ secrets.SERVER_URL }}"
          PLAYGROUND_EMAIL: "${{ secrets.PLAYGROUND_EMAIL }}"
          PLAYGROUND_PASSWORD: "${{ secrets.PLAYGROUND_PASSWORD }}"
          PLAYGROUND_ID: "${{ secrets.PLAYGROUND_ID }}"
          EXTRA_LANGUAGES: "${{ secrets.EXTRA_LANGUAGES }}"
      
      - run: echo "Finished using composite action"
