name: Use composite action

on:
  push:
  workflow_dispatch:
    inputs:
      extra_languages:
        description: 'Optional. A list of comma separated language names visible on buttons or links that change the language of the interview. Overrides the EXTRA_LANGUAGES repo secret.'
        default: ''
      tags:
        description: 'Optional. Use a "tag expression" specify which tagged tests to run (https://cucumber.io/docs/cucumber/api/#tag-expressions)'
        default: ''

jobs:

  composite-test:
    runs-on: ubuntu-latest
        
    name: Test composite
    steps:
      - uses: actions/checkout@v2
      - id: is_id_needed
        uses: plocket/ALKiln@v37
        with:
          SERVER_URL: "${{ secrets.SERVER_URL }}"
          PLAYGROUND_EMAIL: "${{ secrets.PLAYGROUND_EMAIL }}"
          PLAYGROUND_PASSWORD: "${{ secrets.PLAYGROUND_PASSWORD }}"
          PLAYGROUND_ID: "${{ secrets.PLAYGROUND_ID }}"
          EXTRA_LANGUAGES: "${{ secrets.EXTRA_LANGUAGES }}"
      
      - run: echo "Finished using composite action"
